chain:
    bech32_prefix: ethm
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - feegrant
        - gov
        - slashing
        - staking
        - actions
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://168.119.63.112:26657
            max_connections: 20
        grpc:
            address: http://168.119.63.112:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: true
    genesis_file_path: /bdjuno/.bdjuno/genesis.json
    average_block_time: 3s
database:
    url: postgres://bdjuno:bdjuno_password@db:5432/bdjuno?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10
pricefeed:
    tokens:
        - name: PoA
          units:
              - denom: apoa
                exponent: 0
              - denom: poa
                exponent: 6
                price_id: cosmos
        - name: XRP
          units:
              - denom: axrp
                exponent: 0
              - denom: xrp
                exponent: 6
actions:
    port: 3000
