version: '3.6'
services:
    hasura:
        image: hasura/graphql-engine:v2.0.4.cli-migrations-v3
        ports:
            - "8080:8080"
        restart: always
        environment:
            ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
            HASURA_GRAPHQL_DATABASE_URL: postgres://bdjuno:bdjuno_password@db:5432/bdjuno
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "false"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ACTION_BASE_URL: http://bdjuno:3000
        volumes:
            - ./hasura-metadata/metadata:/hasura-metadata

    bdjuno:
        platform: linux/amd64
        image: forbole/bdjuno:chains_evmos_mainnet-v3.2.0-74-g4ce0cc5
        restart: always
        command: /bin/sh /script/init.sh
        volumes:
            - ./bdjuno-config.yaml:/bdjuno/.bdjuno/config.yaml
            - ./init-bdjuno.sh:/script/init.sh

    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_PASSWORD: bdjuno_password
            POSTGRES_USER: bdjuno
            POSTGRES_DB: bdjuno
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
